// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
